server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flexpayDB

jwt:
  secret-key: dont-use-in-prod-a9asd7fulasjdfaklsdfu98q3uhjdiosh897as9d8f7ua9osufdjilasdjf

webhoook:
  secret-encryption-key: jEbSy97ac+f1IDJCbVEMOZ4CJ2VzScYQljWrkxwyVWs=


---
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://postgres.razorpay-core.svc.cluster.local:5432/razorpay-merchant-db
    username: merchant_user
    password: ${MERCHANT_DB_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET}

webhook:
  secret-encryption-key: ${WEBHOOK_SECRET_ENCRYPTION_KEY}
